<h1>Conferences</h1>

<p><a href="<?php echo $this->url('zfcadmin/conferences/crud', array('action' => 'add'))?>">Add new event</a></p>

<?php if (count($this->conferences) > 0) { ?>
<table class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>What</th>
            <th>When</th>
            <th>Where</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->conferences as $event) {?>
        <tr>
            <td><?php echo $event->getId()?></td>
            <td>
                
                <?php if ($this->isAllowed($event, 'view')) { ?>
                    <a href="<?php echo $this->url('zfcadmin/conferences/crud', array('action' => 'view', 'id' => $event->getId()))?>"><?php echo $event->getTitle()?></a>
                <?php } else {
                    echo $event->getTitle();
                }?>
            </td>
            <td><?php echo 'from ' . $event->getDatefrom()->format('Y-m-d') . ' to ' . $event->getDateto()->format('Y-m-d')?></td>
            <td><?php echo $event->getCity()?></td>
            <td>
                
                <?php if ($this->isAllowed($event, 'edit')) { ?>
                <a href="<?php echo $this->url('zfcadmin/conferences/crud', array('action' => 'remove', 'id' => $event->getId()))?>"><i class="icon-trash"></i> Remove</a>
                <br />
                <a href="<?php echo $this->url('zfcadmin/conferences/crud', array('action' => 'edit', 'id' => $event->getId()))?>"><i class="icon-pencil"></i> Edit</a>
                <?php }  ?>
                
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>
<?php } ?>